### ISSUE TITLE
Release binaries

### ISSUE THREAD

**Issue by savchenko** [bladeSk/StayFocused#1]
Greetings. Glad to see I am not the only one bothered by the "applications stealing focus" :)

Would you consider adding binaries to the repository? This would allow, at minimum, see from which tag they were built.

Thanks!

**Comment by bladeSk** [comment]
Sure, in the meantime, you can grab them here https://blade.sk/stay-focused/

**Comment by bladeSk** [comment]
Done: https://github.com/bladeSk/StayFocused/releases
