### ISSUE TITLE
Click to Remove Element: how to export data from chrome and import to edge?

### ISSUE THREAD

**Issue by sisrfeng** [bladeSk/StayFocused#12]
Hi, I love this extension very much!:  https://chrome.google.com/webstore/detail/click-to-remove-element/jcgpghgjhhahcefnfpbncdmhhddedhnk

Could you tell use how to export data from chrome and import to edge?

(I can't find your repo of that extension, so I ask here. Sorry for bothering you.)

**Comment by bladeSk** [comment]
CTRE does not have a repo (yet), please contact me directly. You can find ways of contacting me on https://blade.sk
