### ISSUE TITLE
hook only specific apps

### ISSUE THREAD

**Issue by ritmation** [bladeSk/StayFocused#2]
Hello,

First of all, let me thank you for such a great program and a life saver.
I have a business app at work that steals focus all the time, and it's simply awful, it is interfering with my workflow and is infuriating to the point where all I want to do is smash the computer and go yell at the devs.

With that said, I find that hooking all user apps is kinda slow and unnecessary, as only a limited amount of apps exhibit poor behavior when it comes to stealing focus.
It would be great if hooking only specific apps could be implemented.

Personally, I don't need any fancy user interface settings for that, if it could be implemented via a config file, it would be really awesome.

For example, it could be a setting like this:

```
hookonly=myimagename.exe
hookonly=othermisbehaving.exe
```

or, if xml is preferred,

```
<hookonly>
<imagename>myimagename.exe</imagename>
<imagename>othermisbehaving.exe</imagename>
</hookonly>
```

Thank you.

**Comment by bladeSk** [comment]
I completely agree with you about needlessly hooking everything. I wanted to build a proper UI, but never got around to it. This sounds _much_ more doable. I'll keep your suggestion in mind when I get some free time.

**Comment by Avasam** [comment]
I came here to suggest this. A UI would be nice, but even some configuration file would be sufficient.

In our case ("us" being the entire "Pitfall: The Lost Expedition" speedrunning community), have a game from the Windows 95 - XP days that have an extremely aggressive focus stealing. We can't do anything outside the game. To a point where if the game softlocks, we have to reboot our computer!

A previous workaround was to use DxWnd, but then the game crashes whenever we use our keyboard to do anything else.

"Stay Focused" finally allows us to play while multitasking (ex: streaming, chatting, modding) and without any risk for crashes :D

**Comment by bladeSk** [comment]
Done: https://github.com/bladeSk/StayFocused/releases/tag/Beta3

**Comment by germain-italic** [comment]
I don't get it.

I've created a file named StayFocused.ini next to StayFocused.exe in the StayFocusedBeta3 folder, and I added the program I want (PDR.exe, which is Cyberlink Powerdirector). I restarted the app. The output windows is still listing:

```
Config loaded • mode = whitelist • whitelisted exes:
photoshop.exe
---
```

There is a StayFocused.exe.config which is gibberish to me.

I don't know what to do 🤷🏻‍♂️

**Comment by bladeSk** [comment]
The config is always read from `%APPDATA%\StayFocused.ini`, the "Open Config" button opens that location. `StayFocused.exe.config` contains C# metadata and its name is a technical requirement/limitation of C#, although I agree it's confusing in this context
