### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by stefnotch** [bladeSk/StayFocused#9]
This lovely project was mentioned in a PowerToys issue https://github.com/microsoft/PowerToys/issues/65#issuecomment-730858096
Would it be possible to add a license to StayFocused? (such as the MIT license)

**Comment by bladeSk** [comment]
Done. Thanks for mentioning this. I wasn't aware of the discussion.

They seem to be against using DLL injection, which is completely understandable in a project like PowerToys. Regardless, this project has a license now.

**Comment by stefnotch** [comment]
Lovely, I appreciate the fast response!
